"use client";

import { useState, useEffect } from "react";

export default function CapDrawer({ isOpen, onClose, eventData, activeLocation }) {
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    if (!isOpen) return;
    const handleKeyDown = (e) => {
      if (e.key === "Escape") onClose();
    };
    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [isOpen, onClose]);

  if (!isOpen || !eventData) return null;

  const nowIso = new Date().toISOString();
  const zoneId = eventData.location?.zone_id || "Z42";
  const zoneName = activeLocation?.zone_name || eventData.location?.zone_name || "Target Zone";
  const lat = activeLocation?.latitude || eventData.location?.latitude || 12.9815;
  const lng = activeLocation?.longitude || eventData.location?.longitude || 80.2180;
  const depth = eventData.inundation?.depth_band || "0.5-1.0m";
  const rain = eventData.rainfall?.rainfall_mm_hr || 87.0;
  const priority = eventData.priority || "CRITICAL";

  const xmlContent = `<?xml version="1.0" encoding="UTF-8"?>
<alert xmlns="urn:oasis:names:tc:emergency:cap:1.2">
  <identifier>URN:IN:GOV:TNSDMA:CHENNAI:${eventData.event_id || "E001"}:${Date.now()}</identifier>
  <sender>chennai.flood.ops@tnsdma.tn.gov.in</sender>
  <sent>${nowIso}</sent>
  <status>Draft</status>
  <msgType>Alert</msgType>
  <scope>Public</scope>
  <code>SACHET-PRIORITY-${priority}</code>
  <note>Demonstration CAP payload generated by HydroSurge AI Decision Engine for prototype testing</note>
  <info>
    <category>Met</category>
    <event>Severe Urban Flash Flood Emergency</event>
    <urgency>Immediate</urgency>
    <severity>${priority === "CRITICAL" ? "Extreme" : priority === "HIGH" ? "Severe" : "Moderate"}</severity>
    <certainty>Observed</certainty>
    <eventCode>
      <valueName>IMD_PHENOMENON</valueName>
      <value>FLASH_FLOOD_HIGH_INUNDATION</value>
    </eventCode>
    <expires>${new Date(Date.now() + 3 * 3600 * 1000).toISOString()}</expires>
    <senderName>Tamil Nadu State Disaster Management Authority (TNSDMA)</senderName>
    <headline>Emergency Flash Flood Warning for ${zoneName} (${zoneId})</headline>
    <description>Severe inundation projected at ${depth} due to intense convective precipitation (${rain} mm/hr). Adyar Basin overflow and local drainage choke points active. Immediate defensive action recommended.</description>
    <instruction>Evacuate ground-floor structures immediately. Avoid low-lying underpasses and arterial chokes. Move to designated municipal shelters.</instruction>
    <parameter>
      <valueName>HydroSurge_Event_ID</valueName>
      <value>${eventData.event_id}</value>
    </parameter>
    <parameter>
      <valueName>Peak_Rainfall_Rate_mm_hr</valueName>
      <value>${rain}</value>
    </parameter>
    <parameter>
      <valueName>Projected_Inundation_Depth</valueName>
      <value>${depth}</value>
    </parameter>
    <parameter>
      <valueName>Target_Catchment</valueName>
      <value>Chennai Basin / Adyar River Corridor</value>
    </parameter>
    <area>
      <areaDesc>${zoneName}, Chennai, Tamil Nadu</areaDesc>
      <circle>${lat},${lng},2.5</circle>
      <geocode>
        <valueName>TNSDMA_ZONE_CODE</valueName>
        <value>${zoneId}</value>
      </geocode>
    </area>
  </info>
</alert>`;

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(xmlContent);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    } catch (e) {
      console.error("Failed to copy", e);
    }
  };

  const handleDownload = () => {
    const blob = new Blob([xmlContent], { type: "application/xml;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `CAP_SACHET_ALERT_${eventData.event_id || "E001"}_DEMO.xml`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/60 backdrop-blur-sm p-4 animate-in fade-in duration-150"
      onClick={onClose}
    >
      <div
        className="w-full max-w-3xl rounded-xl panel-technical corner-accents shadow-2xl flex flex-col max-h-[85vh] overflow-hidden border border-border bg-card"
        onClick={(e) => e.stopPropagation()}
      >
        
        {/* Header */}
        <div className="flex items-center justify-between p-4 border-b border-[var(--border)] bg-[var(--card-elevated)]">
          <div className="flex items-center gap-2.5">
            <span className="h-2.5 w-2.5 rounded-full bg-[var(--critical)] animate-pulse ring-2 ring-rose-500/30"></span>
            <div>
              <div className="flex items-center gap-2">
                <span className="label-tactical text-[11px]">CAP v1.2 / SACHET EMERGENCY ALERT GENERATOR</span>
                <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-rose-50 border border-rose-300 text-rose-700 font-bold">
                  OASIS STANDARD
                </span>
              </div>
              <p className="text-xs text-[var(--text-secondary)] mt-0.5 font-mono">
                Standard OASIS Common Alerting Protocol payload format (Prototype validation)
              </p>
            </div>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="text-xs font-mono text-[var(--text-secondary)] hover:text-[var(--text-primary)] px-3 py-1.5 rounded border border-[var(--border)] hover:bg-slate-200 transition-colors cursor-pointer"
          >
            ✕ CLOSE
          </button>
        </div>

        {/* XML Viewer Body */}
        <div className="p-4 overflow-y-auto font-telemetry text-xs bg-slate-900 text-slate-100 leading-relaxed flex-1 border-y border-[var(--border)]">
          <pre className="whitespace-pre-wrap select-all font-mono text-[11px]">
            {xmlContent}
          </pre>
        </div>

        {/* Action Footer */}
        <div className="flex flex-wrap items-center justify-between p-3.5 border-t border-[var(--border)] bg-[var(--card-elevated)] gap-3">
          <div className="flex items-center gap-2 text-xs text-[var(--text-secondary)] font-mono">
            <span className="h-2 w-2 rounded-full bg-[var(--safe)] ring-1 ring-emerald-400"></span>
            <span>Schema-compliant OASIS CAP v1.2 payload for integration testing</span>
          </div>

          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={handleCopy}
              className="cursor-pointer px-3.5 py-1.5 text-xs font-medium rounded-md bg-white border border-[var(--border)] text-[var(--text-primary)] hover:border-slate-400 transition-colors font-mono shadow-2xs"
            >
              {copied ? "✓ COPIED TO CLIPBOARD" : "COPY XML PAYLOAD"}
            </button>

            <button
              type="button"
              onClick={handleDownload}
              className="cursor-pointer px-3.5 py-1.5 text-xs font-bold rounded-md bg-[var(--critical)] text-white hover:brightness-110 shadow-xs transition-all font-mono flex items-center gap-1.5"
            >
              <span>⬇</span>
              <span>DOWNLOAD CAP XML (.xml)</span>
            </button>
          </div>
        </div>

      </div>
    </div>
  );
}
